---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dso-demo-java
  labels:
    app: dso-demo-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo-java
  template:
    metadata:
      labels:
        app: dso-demo-java
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: dso-demo-java
          image: harbor.apps.dso.numerique-interieur.com/form-crtzel/java-demo:master
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-manifest:5432/demo
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080  # Exposes container port
